# Generated by Django 3.0.4 on 2020-05-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('date', models.DateField(auto_now=True)),
                ('typee', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=60)),
            ],
        ),
    ]
