# Generated by Django 3.0.4 on 2020-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractive', '0002_blog_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='abstract',
            field=models.CharField(max_length=250),
        ),
    ]
