# Generated by Django 3.0.4 on 2020-05-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractive', '0003_auto_20200503_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='aboutauthor',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='authorimage',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='links',
            field=models.URLField(default=11),
            preserve_default=False,
        ),
    ]
