# Generated by Django 3.0.4 on 2020-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractive', '0005_auto_20200504_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
